import logging
import os
import re
from typing import Any, Callable, Dict, List, Optional, Tuple, Union
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from google import genai
from google.genai import types
from app.genai_client import DEFAULT_GEMINI_MODEL, get_genai_client
from app.schemas import SlideFidelityReport

logger = logging.getLogger(__name__)


def extract_slide_text_summary(slide: Any) -> str:
  """Extracts all text and shape descriptions from a python-pptx slide object."""
  if not slide or not hasattr(slide, "shapes"):
    return ""
  lines = []
  for idx, shape in enumerate(slide.shapes):
    shape_desc = f"Shape {idx+1} ({shape.name}):"
    if shape.has_text_frame:
      texts = [p.text.strip() for p in shape.text_frame.paragraphs if p.text.strip()]
      if texts:
        lines.append(f"{shape_desc} " + " | ".join(texts))
    elif shape.has_table:
      tbl = shape.table
      tbl_cells = []
      for row in tbl.rows:
        row_str = " , ".join(c.text.strip() for c in row.cells if c.text.strip())
        if row_str:
          tbl_cells.append(f"[{row_str}]")
      if tbl_cells:
        lines.append(f"{shape_desc} Table: " + "; ".join(tbl_cells))
    elif getattr(shape, "has_chart", False):
      try:
        ch = shape.chart
        series_names = [str(s.name) for s in ch.series]
        lines.append(f"{shape_desc} Native Chart ({ch.chart_type}): series={series_names}")
      except Exception:
        lines.append(f"{shape_desc} Native Chart")
  return "\n".join(lines)


def audit_slide_fidelity(
    original_image_input: Union[str, bytes],
    generated_code: str,
    slide: Optional[Any] = None,
    model_name: str = DEFAULT_GEMINI_MODEL,
) -> SlideFidelityReport:
  """Audits generated slide code and structure against the original slide screenshot.

  Args:
      original_image_input: Image path or raw bytes of the original slide.
      generated_code: The python-pptx code string generated by AI.
      slide: Optional executed slide object to inspect shapes and text directly.
      model_name: GenAI model to use for vision evaluation.

  Returns:
      SlideFidelityReport with pass/fail verdict, score, and corrective directives.
  """
  if slide is not None and hasattr(slide, "shapes"):
    shape_count = len(slide.shapes)
    text_summary = extract_slide_text_summary(slide)
    if shape_count < 2 or len(text_summary.strip()) < 10:
      return SlideFidelityReport(
          passed=False,
          score=3,
          zero_omission_verified=False,
          missing_or_truncated_text=["Slide is empty or has fewer than 2 shapes."],
          design_and_layout_issues=["Insufficient shape/text elements rendered."],
          corrective_instructions="Generate all required cards, title text frames, badges, and body bullet points. Do not leave the slide blank.",
      )

  if isinstance(original_image_input, str):
    if not os.path.exists(original_image_input):
      return SlideFidelityReport(passed=True, score=8, zero_omission_verified=True)
    with open(original_image_input, "rb") as f:
      image_bytes = f.read()
  else:
    image_bytes = original_image_input

  clean_code = generated_code
  if "```python" in clean_code:
    clean_code = clean_code.split("```python", 1)[1].split("```", 1)[0].strip()
  elif "```" in clean_code:
    clean_code = clean_code.split("```", 1)[1].split("```", 1)[0].strip()

  slide_text_context = ""
  if slide is not None:
    slide_text_context = f"\n\n[Extracted Slide Content from Executed Shapes]:\n{extract_slide_text_summary(slide)}"

  prompt = f"""
You are the Chief Slide Quality Auditor & Fidelity Critic.
Analyze this 16:9 original slide screenshot and audit the following python-pptx slide builder code:

[GENERATED CODE UNDER AUDIT]
```python
{clean_code}
```
{slide_text_context}

[STRICT AUDIT CRITERIA]
1. ZERO OMISSION CONTENT ACCURACY (100% Verbatim):
   - Is EVERY headline, subtitle, metric number, category badge, card item, bullet point, and footnote from the original image captured in the code?
   - Are any words, phrases, or Korean characters dropped or summarized?
2. SHAPE & TEXT INTEGRATION:
   - For colored cards, buttons, or badges containing text: Is text placed DIRECTLY inside `shape.text_frame`?
   - Check that there are NO disjoint, overlapping textboxes floating awkwardly over shapes.
3. TYPOGRAPHY & LAYOUT FIDELITY:
   - Is `Pretendard` or `Noto Sans KR` used with appropriate bold weights and font sizes?
   - Are word_wrap and margins (`margin_left = Inches(0.05)`) set so text does not clip or overflow?
4. SCORING & PASS THRESHOLD:
   - `passed = True` ONLY if score >= 7 and no critical text or cards are omitted.
   - If score < 7 or critical text is missing, set `passed = False` and provide exact `corrective_instructions`.

Output ONLY a valid JSON object strictly conforming to SlideFidelityReport schema.
"""

  try:
    client = get_genai_client()
    resp = client.models.generate_content(
        model=model_name,
        contents=[
            types.Part.from_bytes(data=image_bytes, mime_type="image/png"),
            prompt,
        ],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=SlideFidelityReport,
            temperature=0.1,
        ),
    )
    if resp.text:
      return SlideFidelityReport.model_validate_json(resp.text)
  except Exception as e:
    logger.warning("[SlideFidelityCritic Error]: %s", e)

  # Default fallback report if API call fails
  return SlideFidelityReport(
      passed=True,
      score=8,
      zero_omission_verified=True,
      corrective_instructions="",
  )


def run_code_on_test_slide(code_str: str) -> Tuple[bool, Optional[Any], Optional[Presentation], str]:
  """Executes python-pptx code on a sandboxed test presentation to verify runtime safety and structure."""
  from app.html_to_pptx_converter import build_styled_native_chart, build_styled_native_table

  clean_code = code_str
  if "```python" in clean_code:
    clean_code = clean_code.split("```python", 1)[1].split("```", 1)[0].strip()
  elif "```" in clean_code:
    clean_code = clean_code.split("```", 1)[1].split("```", 1)[0].strip()

  prs = Presentation()
  prs.slide_width = Inches(13.333333)
  prs.slide_height = Inches(7.5)
  slide = prs.slides.add_slide(prs.slide_layouts[6])

  scope = {
      "prs": prs,
      "slide": slide,
      "Presentation": Presentation,
      "Inches": Inches,
      "Pt": Pt,
      "RGBColor": RGBColor,
      "MSO_SHAPE": MSO_SHAPE,
      "PP_ALIGN": PP_ALIGN,
      "MSO_ANCHOR": MSO_ANCHOR,
      "build_styled_native_table": build_styled_native_table,
      "build_styled_native_chart": build_styled_native_chart,
  }

  try:
    exec(clean_code, scope)
    if "build_slide" in scope:
      func = scope["build_slide"]
      import inspect
      sig = inspect.signature(func)
      if len(sig.parameters) == 1:
        func(slide)
      else:
        func(prs, slide)
    return True, slide, prs, ""
  except Exception as e:
    return False, None, None, str(e)
